baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'Henna By Jasmin'
theme = "gallery"

[params]
  [params.socialIcons]
    facebook = "https://www.facebook.com/JasminHennaDesigns"
    instagram = "https://www.instagram.com/hennabyjasmin_seattle/"
    email = "mailto:user@example.com"
