baseURL = 'https://hennabyjasmin.com/'
languageCode = 'en-us'
title = 'Henna By Jasmin'
theme = "gallery"
timeout = "300s"  # 5 minutes in seconds

[params]
  [params.socialIcons]
    facebook = "https://www.facebook.com/JasminHennaDesigns"
    instagram = "https://www.instagram.com/hennabyjasmin_seattle/"
    email = "mailto:jazzhennna@gmail.com"
